'use client';
import React, { useState } from 'react';

import { Menu, X, MapPin, Building2, Users, Layers3, Plus, Minus, Download, Copy, Check, ExternalLink } from 'lucide-react';


const company = { name: 'Omashwini Multiservices Private Limited', cin: 'U78300UP2023PTC182052', address: '186 Sheo Nagar Naka, Faizabad RS, Faizabad, Uttar Pradesh, 224001, India' };
const nav = [['About us', 'about'], ['Our focus', 'focus'], ['Leadership', 'leadership'], ['Company details', 'company']];
const details = [['Legal name', company.name], ['Corporate Identification Number', company.cin], ['Registration number', '182052'], ['Incorporated on', '12 May 2023'], ['Registrar of Companies', 'Uttar Pradesh'], ['Company type', 'Private non-government company'], ['Listing status', 'Unlisted'], ['Company status', 'Active'], ['Business classification', 'Personal and multiservices business']];
export default function CompanyWebsite({ page = 'home' }: { page?: string }) {
 const [menu, setMenu] = useState(false);
 const [open, setOpen] = useState<number | null>(0);
 const [copied, setCopied] = useState(false);
 const [copyError, setCopyError] = useState(false);
 async function copyCin() { try { await navigator.clipboard.writeText(company.cin); setCopied(true); setCopyError(false); setTimeout(() => setCopied(false), 2500); } catch { setCopyError(true); } }
 function downloadProfile() {
  const text = `${company.name}\nCOMPANY PROFILE\n\n${details.map(([a,b]) => `${a}: ${b}`).join('\n')}\n\nDIRECTORS\nAshwini Kumar Shukla\nAshish Shukla\n\nREGISTERED OFFICE\n${company.address}\n\nCompany information supplied for this profile on 1 October 2026.\n`;
  const url = URL.createObjectURL(new Blob([text], {type:'text/plain;charset=utf-8'})); const a = document.createElement('a'); a.href = url; a.download = 'Omashwini-Company-Profile.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
 }
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <div className="topbar"><span>Rooted in Ayodhya. Looking ahead.</span><span>Incorporated in India · Est. 2023</span></div>
  <header><a href={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/`} className="brand" aria-label="Omashwini home"><span className="brand-icon"><i/><i/><i/></span><span>omashwini<small>MULTISERVICES PRIVATE LIMITED</small></span></a>
   <nav className={menu ? 'nav expanded' : 'nav'} aria-label="Main navigation">{nav.map(([label,id]) => <a key={id} href={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/${id}/`} aria-current={page === id ? 'page' : undefined} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/contact/`} onClick={() => setMenu(false)}>Get in touch</a></nav>
   <button className="menu-toggle" aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button>
  </header>
  <main id="main">
   {page !== 'home' && <div className="page-banner"><a href={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/`}>Home</a><span> / </span><span>{({about:'About us',focus:'Our focus',leadership:'Leadership',company:'Company details',contact:'Contact us'} as Record<string,string>)[page]}</span><h1>{({about:'Rooted in purpose.',focus:'Built around people.',leadership:'Meet our leadership.',company:'Our corporate identity.',contact:'Let’s connect.'} as Record<string,string>)[page]}</h1></div>}

   {(page === 'home') && (<section className="hero" aria-labelledby="hero-title"><div className="hero-photo" style={{backgroundImage: `url(${process.env.NEXT_PUBLIC_BASE_PATH || ''}/hero.jpg)`}}/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light"><span/> BUILT AROUND PEOPLE. DRIVEN BY PURPOSE.</div><h1 id="hero-title">Together,<br/>we move<br/><em>forward.</em></h1><p>A world of possibilities begins with the right connection. Meet Omashwini Multiservices.</p><a className="button lime" href="#about">Discover our company</a></div><div className="hero-bottom"><span>PEOPLE. PURPOSE. PROGRESS.</span><a href="#about">SCROLL TO EXPLORE <span>↓</span></a></div><span className="hero-caption">Architecture for illustration</span></section>)}
   {(page === 'home' || page === 'about') && (<div className="fact-strip"><div><span className="mini-label">OUR FOUNDATION</span><strong>12 May 2023</strong><span>Incorporated with a purpose</span></div><div><span className="mini-label">OUR HOME</span><strong>Ayodhya, Uttar Pradesh</strong><span>Locally rooted. Forward looking.</span></div><div><span className="mini-label">OUR IDENTITY</span><strong>One company. Many possibilities.</strong><span>Personal & multiservices business</span></div></div>)}
   {(page === 'home' || page === 'about') && (<section className="section about" id="about"><div><span className="eyebrow">01 / WHO WE ARE</span><h2>A foundation of trust.<br/><em>A mindset of progress.</em></h2></div><div className="about-copy"><p className="lead">People are at the heart of every business. Purpose is what brings them together.</p><p>Omashwini Multiservices Private Limited is a private non-government company based in Faizabad (Ayodhya), Uttar Pradesh. Incorporated on 12 May 2023, our company operates in the personal and multiservices business category.</p><p>Our ambition is simple: build meaningful relationships and approach every opportunity with clarity, care and a commitment to moving forward.</p><a className="text-link" href={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/company/`}>Explore our company information <Plus size={17}/></a></div></section>)}
   {(page === 'home' || page === 'focus') && (<section className="focus-section" id="focus"><div className="section-heading"><div><span className="eyebrow">02 / OUR FOCUS</span><h2>Many possibilities.<br/><em>One shared purpose.</em></h2></div><p>A people-first outlook, with a practical approach to personal and multiservices business.</p></div><div className="focus-grid">{[{icon:Users, title:'People at the centre', text:'We believe meaningful relationships begin with listening, understanding and respecting individual needs.', tag:'OUR OUTLOOK'},{icon:Layers3,title:'A multiservices mindset',text:'Our business identity brings personal and multiservices together, with openness to understanding different requirements.',tag:'OUR BUSINESS'},{icon:Building2,title:'A lasting foundation',text:'Established as a private limited company in Uttar Pradesh, with a clearly defined corporate identity and leadership.',tag:'OUR STRUCTURE'}].map(({icon:Icon,title,text,tag},i) => <article className="focus-card" key={title}><div className="card-top"><Icon size={32} strokeWidth={1.3}/><span>0{i+1}</span></div><span className="mini-label">{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>)}
   {(page === 'home' || page === 'about' || page === 'focus') && (<section className="values section"><span className="eyebrow">THE WAY WE THINK</span><h2>Progress starts with<br/><span>people.</span> Always.</h2><div className="values-list">{[['Clarity in every conversation','We value a clear understanding of needs, expectations and the path ahead.'],['Relationships with purpose','We aim to build relationships through care, respect and a shared sense of purpose.'],['A forward-looking approach','We look at every new opportunity as a chance to learn, improve and build for the future.']].map(([title,text],i) => <div className="accordion" key={title}><h3><button aria-expanded={open===i} aria-controls={`value-${i}`} onClick={() => setOpen(open===i ? null : i)}><span>0{i+1}</span>{title}{open===i ? <Minus size={20}/> : <Plus size={20}/>}</button></h3><div id={`value-${i}`} hidden={open!==i}><p>{text}</p></div></div>)}</div></section>)}
   {(page === 'home' || page === 'leadership') && (<section className="leadership section" id="leadership"><div className="section-heading"><div><span className="eyebrow">03 / OUR LEADERSHIP</span><h2>People behind<br/><em>the purpose.</em></h2></div><p>Meet the directors of Omashwini Multiservices Private Limited.</p></div><div className="leaders">{[['AK','Ashwini Kumar Shukla'],['AS','Ashish Shukla']].map(([initials,name]) => <article className="leader" key={name}><div className="monogram">{initials}<span>OMASHWINI</span></div><div><span className="mini-label">BOARD OF DIRECTORS</span><h3>{name}</h3><p>Director</p></div></article>)}</div></section>)}
   {(page === 'home' || page === 'company') && (<section className="company section" id="company"><div><span className="eyebrow">04 / CORPORATE INFORMATION</span><h2>Know the company<br/><em>you connect with.</em></h2><p>Our corporate identity, at a glance.</p><button className="button outline" onClick={downloadProfile}><Download size={18}/> Download company profile</button><small className="record-note">Company information as supplied on 1 October 2026.</small></div><dl className="details">{details.map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{label==='Company status' ? <span className="status">{value}</span> : value}{label==='Corporate Identification Number' && <button className="copy" onClick={copyCin} aria-label="Copy CIN">{copied ? <Check size={16}/> : <Copy size={16}/>}</button>}</dd></div>)}<div role="status" className="copy-status">{copied ? 'CIN copied.' : copyError ? 'Please select and copy the CIN above.' : ''}</div></dl></section>)}
   {(true) && (<section className="contact section" id="contact"><div><span className="eyebrow light">LET’S CONNECT</span><h2>Your next chapter.<br/><em>Our shared possibility.</em></h2><p>Start with a connection. Reach us at our registered office in Ayodhya.</p><a className="button lime" href="https://www.google.com/maps/search/?api=1&query=186%20Sheo%20Nagar%20Naka%20Faizabad%20Uttar%20Pradesh%20224001" target="_blank" rel="noreferrer">Find our location <ExternalLink size={16}/></a></div><div className="office"><MapPin size={26}/><span className="mini-label">REGISTERED OFFICE</span><h3>Ayodhya<br/>(Faizabad), India</h3><address>{company.address}</address></div></section>)}
  </main><footer><div className="footer-top"><a className="brand" href="#"><span className="brand-icon"><i/><i/><i/></span><span>omashwini<small>MULTISERVICES PRIVATE LIMITED</small></span></a><p>People. Purpose. Progress.</p><a href="#main">Back to top ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {company.name}</span><span>CIN: {company.cin}</span></div></footer>
 </>;
}
